"""Training infrastructure for the cortex's learned grammar model.

Phase 2 of the cortex roadmap: a tiny grammar-only language model
trained to map between natural English and Sara's structured format.

The model has zero world knowledge. It is trained ONLY on grammar.
This is the proof-of-concept that you don't need a billion parameters
to do useful language work — you just need to know how sentences are
shaped.

The training data is generated by the synthesize module from the
existing rule-based parser and the brain's vocabulary. No external
datasets, no human annotation. Sara generates her own training data.
"""
