"""Synthesize training data for the cortex's learned grammar model.

Generates pairs of (natural English ↔ structured form) from a base
vocabulary. The structured form is the same one the rule-based parser
produces. The natural English forms are generated by template variation.

This is the bootstrap: the existing parser generates the ground truth,
and we generate many natural language paraphrases of each ground-truth
example. A tiny grammar-only model can then be trained on these pairs.

No external data. No human annotation. Sara generates her own training
set by varying templates over her own vocabulary.

Output format: JSONL with one example per line:
    {"input": "the apple is red", "subject": "apple", "verb": "is",
     "object": "red", "negated": false}

Usage:
    python -m sara_brain.cortex.training.synthesize \\
        --vocab-file vocab.json \\
        --output train.jsonl \\
        --count 10000
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path


# ── Template families ──
# Each template is a function (subject, obj, negated) -> str.
# More templates = richer training data.

TEACH_TEMPLATES = [
    "{subject} is {object}",
    "{subject} are {object}",
    "the {subject} is {object}",
    "the {subject} are {object}",
    "a {subject} is {object}",
    "an {subject} is {object}",
    "{subject}s are {object}",
    "{subject} is a {object}",
    "{subject} is an {object}",
    "{subject} is the {object}",
    "{subject} was {object}",
    "{subject} were {object}",
    "the {subject} was a {object}",
    "{subject} was originally a {object}",
    "i learned that {subject} is {object}",
    "{subject}, which is {object}",
]

REFUTE_TEMPLATES = [
    "{subject} is not {object}",
    "{subject} are not {object}",
    "the {subject} is not {object}",
    "{subject} was not {object}",
    "{subject} were not {object}",
    "{subject} isn't {object}",
    "{subject} aren't {object}",
    "{subject} wasn't {object}",
    "{subject} is never {object}",
    "no, {subject} is {object}",  # negative reply, not literal negation
]

QUESTION_TEMPLATES = [
    "what is {subject}",
    "what is a {subject}",
    "what are {subject}s",
    "what was {subject}",
    "tell me about {subject}",
    "describe {subject}",
    "what do you know about {subject}",
    "explain {subject}",
    "define {subject}",
    "is {subject} {object}",
    "is the {subject} {object}",
]


# ── Default vocabulary for bootstrap demos ──
# Real training would load from a richer source. This is enough to
# generate thousands of valid pairs for a proof-of-concept.

DEFAULT_SUBJECTS = [
    "apple", "dog", "cat", "tree", "river", "mountain", "city",
    "bird", "fish", "house", "car", "computer", "book", "school",
    "edubba", "sumerian", "babylonian", "assyrian",
    "rna", "dna", "protein", "enzyme", "molecule",
    "neuron", "segment", "path", "concept",
]

DEFAULT_OBJECTS = [
    "red", "blue", "green", "small", "large", "round", "square",
    "ancient", "modern", "wooden", "metal", "fast", "slow",
    "alive", "dead", "warm", "cold", "sweet", "bitter",
    "school", "city", "language", "tool", "structure",
    "biological", "chemical", "physical", "mechanical",
    "fruit", "animal", "place", "object", "idea",
]


def synthesize(
    subjects: list[str] | None = None,
    objects: list[str] | None = None,
    count: int = 1000,
    seed: int = 42,
) -> list[dict]:
    """Generate training pairs.

    Returns a list of dicts. Each dict has:
        input:    natural-language form
        subject:  parsed subject
        verb:     "is" or "is_not" or "?"
        object:   parsed object (None for questions)
        kind:     "teach" / "refute" / "question"
    """
    rng = random.Random(seed)
    subjects = subjects or DEFAULT_SUBJECTS
    objects = objects or DEFAULT_OBJECTS

    examples: list[dict] = []
    while len(examples) < count:
        kind = rng.choices(
            ["teach", "refute", "question"],
            weights=[0.6, 0.2, 0.2],
        )[0]
        subject = rng.choice(subjects)
        obj = rng.choice(objects) if kind != "question" else rng.choice([None] + objects)

        if kind == "teach":
            template = rng.choice(TEACH_TEMPLATES)
            text = template.format(subject=subject, object=obj)
            examples.append({
                "input": text,
                "subject": subject,
                "verb": "is",
                "object": obj,
                "kind": "teach",
            })
        elif kind == "refute":
            template = rng.choice(REFUTE_TEMPLATES)
            text = template.format(subject=subject, object=obj)
            examples.append({
                "input": text,
                "subject": subject,
                "verb": "is_not",
                "object": obj,
                "kind": "refute",
            })
        else:  # question
            template = rng.choice(QUESTION_TEMPLATES)
            try:
                text = template.format(subject=subject, object=obj or "what")
            except KeyError:
                text = template.format(subject=subject)
            examples.append({
                "input": text,
                "subject": subject,
                "verb": "?",
                "object": obj,
                "kind": "question",
            })

    return examples


def write_jsonl(examples: list[dict], path: Path) -> None:
    with path.open("w", encoding="utf-8") as f:
        for ex in examples:
            f.write(json.dumps(ex) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Synthesize training data for the cortex grammar model."
    )
    parser.add_argument(
        "--count", type=int, default=1000,
        help="Number of training pairs to generate (default: 1000)",
    )
    parser.add_argument(
        "--output", type=Path, default=Path("cortex_train.jsonl"),
        help="Output JSONL file",
    )
    parser.add_argument(
        "--seed", type=int, default=42,
        help="Random seed for reproducibility",
    )
    args = parser.parse_args()

    examples = synthesize(count=args.count, seed=args.seed)
    write_jsonl(examples, args.output)
    print(f"Wrote {len(examples)} examples to {args.output}")


if __name__ == "__main__":
    main()
