"""Substrate-driven labeler for the (future) neural synthesizer head.

Walks Sara's brain.db edge by edge, clusters edges by subject concept,
and emits (edge_list, prose) training pairs using the same template
table the template synthesizer uses for inference. The eventual neural
synthesizer learns this mapping with sentence-shape variety from the
grammar LM — replacing the templates with a small generative head.

Output format mirrors what the synthesizer sees at inference time so
the model trains on its actual deployment distribution.
"""
from __future__ import annotations

import random
import sqlite3
from collections import defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path

from .synthesizer import Edge, render_edges


@dataclass
class SynthExample:
    edges: list[Edge]
    prose: str
    subject: str        # the concept this cluster is about

    def to_dict(self) -> dict:
        return {
            "edges": [asdict(e) for e in self.edges],
            "prose": self.prose,
            "subject": self.subject,
        }


_NOISE_RELATIONS_FOR_LABELER = {"part_of", "describes"}


def load_substrate_edges(db_path: Path) -> list[Edge]:
    conn = sqlite3.connect(str(db_path))
    rows = conn.execute(
        "SELECT n1.label, s.relation, n2.label, s.strength "
        "FROM segments s "
        "JOIN neurons n1 ON s.source_id = n1.id "
        "JOIN neurons n2 ON s.target_id = n2.id"
    ).fetchall()
    conn.close()
    out: list[Edge] = []
    for src, rel, tgt, strength in rows:
        if rel in _NOISE_RELATIONS_FOR_LABELER:
            continue
        out.append(Edge(
            src=src.replace("_attribute", ""),
            rel=rel,
            tgt=tgt.replace("_attribute", ""),
            refuted=(strength is not None and strength < 0),
        ))
    return out


def cluster_by_subject(edges: list[Edge]) -> dict[str, list[Edge]]:
    by_src: dict[str, list[Edge]] = defaultdict(list)
    for e in edges:
        by_src[e.src].append(e)
    return by_src


def generate_examples(
    db_path: Path,
    min_edges_per_cluster: int = 1,
    max_edges_per_cluster: int = 12,
    rng: random.Random | None = None,
) -> list[SynthExample]:
    """Build (edge_cluster, prose) pairs from a Sara substrate. Each cluster
    is the edges around one subject concept; prose is generated by the
    same template renderer the inference path uses."""
    rng = rng or random.Random(0)
    edges = load_substrate_edges(db_path)
    clusters = cluster_by_subject(edges)
    examples: list[SynthExample] = []
    for subject, cluster in clusters.items():
        if len(cluster) < min_edges_per_cluster:
            continue
        if len(cluster) > max_edges_per_cluster:
            # Sub-sample large clusters into multiple smaller examples so
            # the model sees varied edge-set sizes, not just the full
            # neighborhood.
            rng.shuffle(cluster)
            for i in range(0, len(cluster), max_edges_per_cluster):
                chunk = cluster[i:i + max_edges_per_cluster]
                prose = render_edges(chunk, topic=subject)
                if prose:
                    examples.append(SynthExample(
                        edges=chunk, prose=prose, subject=subject,
                    ))
        else:
            prose = render_edges(cluster, topic=subject)
            if prose:
                examples.append(SynthExample(
                    edges=cluster, prose=prose, subject=subject,
                ))
    return examples


def write_jsonl(examples: list[SynthExample], path: Path) -> None:
    import json
    with path.open("w", encoding="utf-8") as f:
        for ex in examples:
            f.write(json.dumps(ex.to_dict()) + "\n")


def main() -> None:
    import argparse
    p = argparse.ArgumentParser(
        description="Generate (edge_list, prose) training pairs from a "
                    "Sara brain.db for the neural synthesizer head.")
    p.add_argument("--brain", type=Path, required=True)
    p.add_argument("--output", type=Path, required=True,
                   help="JSONL output path (one pair per line)")
    p.add_argument("--min-edges", type=int, default=1)
    p.add_argument("--max-edges", type=int, default=12)
    p.add_argument("--seed", type=int, default=0)
    args = p.parse_args()

    examples = generate_examples(
        args.brain,
        min_edges_per_cluster=args.min_edges,
        max_edges_per_cluster=args.max_edges,
        rng=random.Random(args.seed),
    )
    write_jsonl(examples, args.output)
    print(f"wrote {len(examples)} examples to {args.output}")
    if examples:
        avg = sum(len(e.edges) for e in examples) / len(examples)
        n_subjects = len({e.subject for e in examples})
        print(f"  {n_subjects} subjects, avg {avg:.1f} edges/cluster")


if __name__ == "__main__":
    main()
