"""Generate training data for the elimination-based reasoner.

Each choice is labeled: CONTRADICTED, CONSISTENT, or UNKNOWN.
The model learns to detect contradiction with the facts, not just
string matching. The correct answer is the one NOT contradicted.

Training examples have:
- Facts (from substrate)
- Multiple choices
- Per-choice label: 0=CONTRADICTED, 1=CONSISTENT, 2=UNKNOWN
- The correct answer is the CONSISTENT one

Contradictions are generated by taking a real fact and CHANGING
the object — so the model must learn "the fact says X but the
choice says Y, therefore contradicted."

Usage:
    python scripts/generate_eliminator_data.py \
        --num-examples 500000 \
        --out training_data/eliminator_500k.jsonl
"""
from __future__ import annotations

import argparse
import json
import random
import sys
import time
from pathlib import Path

CONSONANTS = "bcdfghjklmnprstvwz"
VOWELS = "aeiou"


def _syl(rng):
    return rng.choice(CONSONANTS) + rng.choice(VOWELS) + rng.choice(CONSONANTS + VOWELS)


def word(rng, syls=0):
    return "".join(_syl(rng) for _ in range(syls or rng.randint(2, 3)))


def concept(rng):
    n = rng.choices([1, 2, 3], weights=[0.3, 0.5, 0.2])[0]
    return " ".join(word(rng) for _ in range(n))


RELATIONS = [
    "is_a", "contains", "produces", "requires", "involves",
    "causes", "prevents", "occurs_in", "part_of", "enables",
    "interacts_with", "regulates", "provides",
]


def generate_example(rng):
    # Create domain
    n_concepts = rng.randint(8, 14)
    concepts = [concept(rng) for _ in range(n_concepts)]

    # Create facts (triples)
    triples = []
    used = set()
    for i in range(min(n_concepts - 1, 7)):
        rel = rng.choice(RELATIONS)
        triples.append((concepts[i], rel, concepts[i + 1]))
        used.add((i, i + 1))
    for _ in range(rng.randint(2, 5)):
        a, b = rng.sample(range(n_concepts), 2)
        if (a, b) not in used:
            triples.append((concepts[a], rng.choice(RELATIONS), concepts[b]))
            used.add((a, b))

    if len(triples) < 4:
        return None

    # Pick target triple — this is the "truth"
    target_idx = rng.randint(0, len(triples) - 1)
    target_s, target_r, target_o = triples[target_idx]

    # Question about the target
    question = f"What does {target_s} {target_r}?"

    # Render facts
    fact_lines = [f"{s} {r} {o}" for s, r, o in triples]
    rng.shuffle(fact_lines)
    facts = "\n".join(f"  - {f}" for f in fact_lines[:8])

    # Build choices with explicit labels
    n_choices = rng.randint(3, 6)
    choices = []
    labels = []

    # 1. CONSISTENT choice: the actual correct object
    choices.append(target_o)
    labels.append(1)  # CONSISTENT

    # 2. CONTRADICTED choices: objects from OTHER triples with the SAME subject
    # (the fact says subject→relation→X, but this choice says Y instead of X)
    same_subj_triples = [(s, r, o) for s, r, o in triples
                         if s == target_s and o != target_o]
    contradicted_added = 0
    for _, _, wrong_o in same_subj_triples[:2]:
        if wrong_o not in choices:
            choices.append(wrong_o)
            labels.append(0)  # CONTRADICTED (different object for same subject+relation)
            contradicted_added += 1

    # 3. More CONTRADICTED: random concepts that have their OWN facts
    # (they ARE something else, so they can't be the answer)
    other_objects = [o for s, r, o in triples if o != target_o and o not in choices]
    for obj in rng.sample(other_objects, min(2, len(other_objects))):
        if len(choices) >= n_choices:
            break
        choices.append(obj)
        labels.append(0)  # CONTRADICTED

    # 4. UNKNOWN: completely new concepts not in any fact
    while len(choices) < n_choices:
        new_c = concept(rng)
        if new_c not in choices and new_c not in [o for _, _, o in triples]:
            choices.append(new_c)
            labels.append(2)  # UNKNOWN

    # Shuffle choices (keep labels aligned)
    combined = list(zip(choices, labels))
    rng.shuffle(combined)
    choices, labels = zip(*combined)
    choices, labels = list(choices), list(labels)

    # Find the correct answer (the CONSISTENT one)
    correct_idx = labels.index(1)

    # Format choices
    choice_str = " | ".join(f"{chr(65+i)}. {c}" for i, c in enumerate(choices))

    return {
        "facts": facts,
        "question": question,
        "choices": choice_str,
        "choices_list": choices,
        "labels": labels,  # 0=CONTRADICTED, 1=CONSISTENT, 2=UNKNOWN
        "correct_idx": correct_idx,
        "correct_letter": chr(65 + correct_idx),
        "n_choices": len(choices),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--num-examples", type=int, default=500000)
    ap.add_argument("--out", required=True)
    ap.add_argument("--seed", type=int, default=577215)
    args = ap.parse_args()

    rng = random.Random(args.seed)
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    out_f = open(args.out, "w")
    generated = 0
    t0 = time.time()

    while generated < args.num_examples:
        ex = generate_example(rng)
        if ex:
            out_f.write(json.dumps(ex) + "\n")
            generated += 1
        if generated % 50000 == 0 and generated > 0:
            print(f"[{generated}/{args.num_examples}] ({time.time()-t0:.0f}s)", file=sys.stderr)

    out_f.close()
    print(f"\nDone. {generated} examples in {time.time()-t0:.0f}s.", file=sys.stderr)


if __name__ == "__main__":
    main()
