#!/usr/bin/env bash
# v048.1 — launch HamRobySum-EN-Complex-v1 training in tmux.
#
# Wraps train_hamrobysum.sh with v048.1-specific defaults: same
# corpus path as v048 (regenerated by build_complex_corpus.sh with
# the v048.1 templates), new ckpt name, resume from v048 to preserve
# learned simple+two-scene patterns.
#
# Env vars (all optional):
#   PAIRS        — corpus JSONL path     (default: /tmp/synth_pairs_complex.jsonl)
#   CKPT_NAME    — output ckpt stem      (default: hamroby_sum_en_complex_v1)
#   STEPS        — training steps        (default: 4000)
#   SESSION      — tmux session name     (default: sara-synth-complex-v1)
#   RESUME_FROM  — base ckpt to resume   (default: v048 at 004000)
#   UNFREEZE     — top-N unfreeze        (default: 2)
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

export PAIRS="${PAIRS:-/tmp/synth_pairs_complex.jsonl}"
export CKPT_NAME="${CKPT_NAME:-hamroby_sum_en_complex_v1}"
export STEPS="${STEPS:-4000}"
export SESSION="${SESSION:-sara-synth-complex-v1}"
export RESUME_FROM="${RESUME_FROM:-src/sara_brain/cortex/checkpoints/hamroby_sum_en_complex_004000.pt}"
export UNFREEZE="${UNFREEZE:-2}"

if [ ! -f "$PAIRS" ]; then
  echo "corpus not found: $PAIRS" >&2
  echo "build it first: ./scripts/build_complex_corpus.sh" >&2
  exit 1
fi

if [ ! -f "$RESUME_FROM" ]; then
  echo "v048 base checkpoint not found: $RESUME_FROM" >&2
  exit 1
fi

exec ./scripts/train_hamrobysum.sh
